version: '3.8'

services:
  backend:
    build:
      context: ./mon-backend-fastapi
    container_name: backend-fastapi
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./mon-frontend-react
    container_name: frontend-react
    ports:
      - "3000:80"
    depends_on:
      - backend
